version: '3.9'

services:
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"

  db-postgres:
    image: postgres:latest
    container_name: db-postgres
    environment:
      POSTGRES_DB: FastAPI_APP
      POSTGRES_USER: useradmin
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data:
