"""image_m2m_user and Image changes

Revision ID: 47e2d79db895
Revises: b8d2f7b61f14
Create Date: 2024-05-19 21:53:33.545380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e2d79db895'
down_revision: Union[str, None] = 'b8d2f7b61f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
