"""add is_active

Revision ID: ecce6ed8c8a8
Revises: 3746880c5c0a
Create Date: 2024-05-21 20:01:31.048094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecce6ed8c8a8'
down_revision: Union[str, None] = '3746880c5c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_m2m_user', sa.Column('user_id_like', sa.Integer(), nullable=True))
    op.add_column('image_m2m_user', sa.Column('user_id_dislike', sa.Integer(), nullable=True))
    op.drop_constraint('unique_like_dislike', 'image_m2m_user', type_='unique')
    op.create_unique_constraint('unique_like_dislike', 'image_m2m_user', ['image_id', 'user_id_like', 'user_id_dislike'])
    op.create_unique_constraint('unique_dislike', 'image_m2m_user', ['image_id', 'user_id_dislike'])
    op.create_unique_constraint('unique_like', 'image_m2m_user', ['image_id', 'user_id_like'])
    op.drop_constraint('image_m2m_user_user_id_fkey', 'image_m2m_user', type_='foreignkey')
    op.create_foreign_key(None, 'image_m2m_user', 'users', ['user_id_dislike'], ['id'])
    op.create_foreign_key(None, 'image_m2m_user', 'users', ['user_id_like'], ['id'])
    op.drop_column('image_m2m_user', 'user_id')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('image_m2m_user', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'image_m2m_user', type_='foreignkey')
    op.drop_constraint(None, 'image_m2m_user', type_='foreignkey')
    op.create_foreign_key('image_m2m_user_user_id_fkey', 'image_m2m_user', 'users', ['user_id'], ['id'])
    op.drop_constraint('unique_like', 'image_m2m_user', type_='unique')
    op.drop_constraint('unique_dislike', 'image_m2m_user', type_='unique')
    op.drop_constraint('unique_like_dislike', 'image_m2m_user', type_='unique')
    op.create_unique_constraint('unique_like_dislike', 'image_m2m_user', ['image_id', 'user_id'])
    op.drop_column('image_m2m_user', 'user_id_dislike')
    op.drop_column('image_m2m_user', 'user_id_like')
    # ### end Alembic commands ###
